### ISSUE TITLE
Make an icon light up or be highlighted somehow while selected.

### ISSUE THREAD

**Issue by ericahagen** [mapkibera/counties#11]
Currently you click the icon, and see its info, but then forget which one you clicked since it looks identical to all the ones you didn't click on.

**Comment by mikelmaron** [comment]
Fixed by https://github.com/mapkibera/counties/commit/3dcabfa4f4c4b7419e70ce4bb415020b9f35aaa8 

@ericahagen check the live site. does this look ok?

**Comment by ericahagen** [comment]
the underline? it'll do. I think becoming more bold/large might be easier to see but it's ok.
