### ISSUE TITLE
Add county boundaries

### ISSUE THREAD

**Issue by ericahagen** [mapkibera/counties#13]
Need some type of county boundary on the map. Currently can't tell edge of Makueni county. Also important as we add the second county.

**Comment by mikelmaron** [comment]
The dashed purple line is the county boundary. Is it not accurate?

![screen shot 2018-07-16 at 3 23 11 pm](https://user-images.githubusercontent.com/22896/42778784-38d3740a-890c-11e8-9a12-753dab6a2ce0.png)

**Comment by mikelmaron** [comment]
Boundary added. Any feedback?

**Comment by ericahagen** [comment]
I'm still seeing it the same, without a clear boundary to the county.

**Comment by ericahagen** [comment]
There are a lot of lines going on but I don't see them clearly nor do I automatically know what they mean.
