### ISSUE TITLE
Baringo POI photos error

### ISSUE THREAD

**Issue by ericahagen** [mapkibera/counties#29]
https://mapkibera.github.io/counties/baringo/#13/0.53965/35.67971

For instance... several others too...

**Comment by mikelmaron** [comment]
I don't see the problem exactly. Can you share screenshots? @ericahagen

**Comment by mikelmaron** [comment]
solved. we were not aware of "image:pointofinterest" or any image tag on POIs. 

_side note_

we need to start doing tagging definitions _before_ anything else in a google sheet. from there, it defines our forms for collecting data in ODK, for editing JOSM, for QA, and for building apps
