### ISSUE TITLE
errors from build: 20191005

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/counties#33]
## Project Matching

List of projects from project sheet with no match in OSM

INFO:root:match_projects start: marigat
WARN: 12 marigat no project id match 99 Kibingor Borehole
WARN: 22 marigat no project id match 128 Marigat Sub County Hospital
WARN: 27 marigat no project id match 135 Kapkures Dispensary
WARN: 30 marigat no project id match 144 Bekibon Storage Tank
WARN: 37 marigat no project id match 153 Tinomoi Dispensary
WARN: 38 marigat no project id match 155 Katkamuma ECDE
WARN: 45 marigat no project id match 202 Kimalel Cultural Centre
WARN: 48 marigat no project id match 206 Kimalel Cultural Centre
WARN: 49 marigat no project id match 206 Mangar water project
WARN: 53 marigat no project id match 224 Ndambul Borehole
WARN: 60 marigat no project id match Other_1 Marigat Sub County Hospital Septic Tank
WARN: 61 marigat no project id match hospital Marigat Sub County Hospital Ward Block
WARN: 62 marigat no project id match Other_1 Marigat Sub County Hospital Mortuary
WARN: 63 marigat no project id match sports_ground Marigat Playground
INFO:root:match_projects complete: marigat
INFO:root:match_projects start: eldama
INFO:root:match_projects complete: eldama
INFO:root:match_projects start: kabernet
WARN: 10 kabernet no project id match 26126170 Kabarnet Market Sheds
WARN: 47 kabernet no project id match 26190962 Kabarnet town monument
INFO:root:match_projects complete: kabernet
INFO:root:match_projects start: mogotio
WARN: 55 mogotio no project id match 58 Kiptoim borehole
WARN: 67 mogotio no project id match 69 Boda boda Shed
WARN: 90 mogotio no project id match 196 Ngenyboteweret Dam
WARN: 91 mogotio no project id match earth_dam Ngenypoteweret Dam
WARN: 92 mogotio no project id match road Mogotio - Sagasagik Road
WARN: 93 mogotio no project id match road Kapnaburuki Kapngasia Road
INFO:root:match_projects complete: mogotio
INFO:root:match_projects start: mbooni
INFO:root:match_projects complete: mbooni
INFO:root:match_projects start: wote
WARN: 17 wote no project id match 21744024 Kasarani car wash
INFO:root:match_projects complete: wote

## Images

~~INFO:root:url2file start: 1231052002481.jpg
IMAGE ERROR,orig missing,http://www.osm.org/5798788035,image:project,1231052002481.jpg
INFO:root:url2file start: 1231053714486.jpg
IMAGE ERROR,orig missing,http://www.osm.org/5798788033,image:project,1231053714486.jpg
INFO:root:url2file start: http://kc.humanitarianresponse.info/attachment/orginal?media_file=mapkibera/attachments/\1531988212032.jpg
404 http://kc.humanitarianresponse.info/attachment/orginal?media_file=mapkibera/attachments/\1531988212032.jpg
IMAGE ERROR,orig missing,http://www.osm.org/5781138884,image:project,http://kc.humanitarianresponse.info/attachment/orginal?media_file=mapkibera/attachments/\1531988212032.jpg~~

## Categories

The categories applied in this round of mapping do not match what we had previously. We need to discuss how to resolve this.

![image](https://user-images.githubusercontent.com/22896/66258275-61d23e80-e771-11e9-9d97-14c3f4e4e718.png)

**Comment by ericahagen** [comment]
![image](https://user-images.githubusercontent.com/8549556/66335216-87de1700-e908-11e9-83af-5512a9b19548.png)

**Comment by mikelmaron** [comment]
These were the previous categories used in Baringo. A couple match, but most are slightly different. Should these categories be consistent across the whole county?

* Education, Sports, Culture and Social services
* Water and Irrigation
* Agriculture, Livestock and Fisheries
* Health Services
* Transport, Public Works and Infrasctructure
* Lands, Housing and Urban Development
* Environment, Natural Resource, Tourism and Wildlife Management
* Devolution, Public Service Management and Administration, Youths and ICT
