### ISSUE TITLE
Adjust govt depts Baringo to new ones

### ISSUE THREAD

**Issue by ericahagen** [mapkibera/counties#37]
https://docs.google.com/spreadsheets/d/1wSW9vwmp_HAMdwm8jtbd3jGjkx4yR4bBMBJneem-SI8/edit#gid=0

- use full name, not abbreviation, in legend
- for those split in two, for now keep as three separate depts unless further update by Zack

- make sure to clean up the original data eventually

**Comment by mikelmaron** [comment]
@ericahagen 

> Devolution, Public Service Management and Administration, Youths and ICT

Does this stay the same? There's no listing of successor department

**Comment by mikelmaron** [comment]
Also in West Pokot, these bad categories (note trailing space)

* "HS "
* "TIICD "
* "road"

**Comment by adeleakinyi** [comment]
> @ericahagen
> 
> > Devolution, Public Service Management and Administration, Youths and ICT
> 
> Does this stay the same? There's no listing of successor department

This might not exist anymore at all, but it would be better to have confirmation from the county.

**Comment by adeleakinyi** [comment]
> Also in West Pokot, these bad categories (note trailing space)
> 
> * "HS "
> * "TIICD "
> * "road"

First two found and corrected. I also checked all the "road" type_of_project in both WP spreadsheets and they're all fine.

**Comment by ericahagen** [comment]
> > Also in West Pokot, these bad categories (note trailing space)
> > 
> > * "HS "
> > * "TIICD "
> > * "road"
> 
> First two found and corrected. I also checked all the "road" type_of_project in both WP spreadsheets and they're all fine.

Do these need to be also corrected in OSM? Mikel?
