### ISSUE TITLE
Add budget info to West POkot site like it is on baringo site

### ISSUE THREAD

**Issue by ericahagen** [mapkibera/counties#42]
I think you'll be using a different column though called tender sum.

**Comment by adeleakinyi** [comment]
@mikelmaron, sometimes on the csv there are 2 or more budgets in the same cell 
--> when for instance for a road that had works on different Km, they budgeted different sums:

e.g. 16,941.00 / 15,000.00 / 475,992.00 / 96,200.00 / 31,000.00 / 31,000.00

For better reading on the website, let us know if you prefer us to keep them separated and how (with which separator, now there is "/") or if it's better to sum them and leave only one sum

**Comment by mikelmaron** [comment]
done
