### ISSUE TITLE
projects w/o OSM features

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/counties#8]
WARN: no project id match 21643345
WARN: no project id match 21647295
WARN: no project id match 21640000
WARN: no project id match 22762087
WARN: no project id match 22762180
WARN: no project id match 22946694
WARN: no project id match 22946839
WARN: no project id match 22947198
WARN: no project id match 22947305
WARN: no project id match 22947667
WARN: no project id match 22947695
WARN: no project id match 22951663
WARN: no project id match 22952267

**Comment by ericahagen** [comment]
Zack has found most of these and put into OSM. Three he couldn't find so far. He will send OSM file.

**Comment by ericahagen** [comment]
This are the ones that I found:
22762087
22762180
22946694
22946839
22947198
22947305
22947667
22947695
22951663
22952267

And I didn't find this one

21643345
21647295
21640000

**Comment by mikelmaron** [comment]
ok -- updated data and deployed. Closing here for now.

**Comment by ericahagen** [comment]
I found the other three - asking Zack to please update them as well.
